# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.3

twitter_username: jekyllrb
github_username:  jekyll
repository: wahyuadt/extra182
encoding: UTF-8


# Build settings

#theme: jekyll-theme-midnight


#title: extra182
#description: >
    #This site is developed for the extra 1% assignment of Operating Systems course 
    
title : GitHub Pages + Jekyll Tutorial
description : This is a tutorial page for making a simple website
    
author: nyem
# theme: jekyll-theme-midnight
# github: [metadata]

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  
include:
 - _navbar.md
 
#jailed: false
#gfm_quirks: paragraph_end

#lsi: false
#safe: true
#source: coba2
incremental: false
highlighter: rouge
#gist:
  #noscript: false
#kramdown:
  #input: GFM
  #hard_wrap: false
  #math_engine: mathjax
  #syntax_highlighter: rouge

theme: jekyll-theme-cayman